export const initialUpgrades = [{
  id: 1,
  name: 'Desecrated Flame',
  description: 'Increase damage per click by',
  level: 0,
  cost: 5,
  value: 0,
  growthRate: 1,
}, {
  id: 2,
  name: 'Gold Bag',
  description: 'Increase damage per second by',
  level: 0,
  cost: 50,
  value: 0,
  growthRate: 5,
}, {
  id: 3,
  name: 'Helmet Of The Wind',
  description: 'Increase damage per second by',
  level: 0,
  cost: 250,
  value: 0,
  growthRate: 22,
}, {
  id: 4,
  name: 'Cursed Sword',
  description: 'Increase damage per second by',
  level: 0,
  cost: 1000,
  value: 0,
  growthRate: 74,
}, {
  id: 5,
  name: 'Afflatus',
  description: 'Increase damage per second by',
  level: 0,
  cost: 2000,
  value: 0,
  growthRate: 126,
}, {
  id: 6,
  name: 'Ebony Breastplate',
  description: 'Increase damage per second by',
  level: 0,
  cost: 4000,
  value: 0,
  growthRate: 245,
}, {
  id: 7,
  name: 'Fallen Hand',
  description: 'Increase damage per second by',
  level: 0,
  cost: 10000,
  value: 0,
  growthRate: 508,
}, {
  id: 8,
  name: 'Old Boots Of The Deceased',
  description: 'Increase damage per second by',
  level: 0,
  cost: 20000,
  value: 0,
  growthRate: 976,
}, {
  id: 9,
  name: 'Ring Of Will',
  description: 'Increase damage per second by',
  level: 0,
  cost: 40000,
  value: 0,
  growthRate: 1580,
}, {
  id: 10,
  name: 'Beckoning Amulet Of Pain',
  description: 'Increase damage per second by',
  level: 0,
  cost: 100000,
  value: 0,
  growthRate: 3725,
}, {
  id: 11,
  name: 'Screaming Lantern',
  description: 'Increase damage per second by',
  level: 0,
  cost: 200000,
  value: 0,
  growthRate: 5851,
}, {
  id: 12,
  name: 'Key Holding',
  description: 'Increase damage per second by',
  level: 0,
  cost: 400000,
  value: 0,
  growthRate: 10859,
}, {
  id: 13,
  name: 'Lost Empire Banner',
  description: 'Increase damage per second by',
  level: 0,
  cost: 6500000000,
  value: 0,
  growthRate: 1, // ?
}, {
  id: 14,
  name: 'Enchantment Prism',
  description: 'Increase damage per second by',
  level: 0,
  cost: 2500000,
  value: 0,
  growthRate: 47143,
}, {
  id: 15,
  name: 'Amulet Of Time',
  description: 'Increase damage per second by',
  level: 0,
  cost: 15000000,
  value: 0,
  growthRate: 186900,
}, {
  id: 16,
  name: 'Secret Restraining Seal',
  description: 'Increase damage per second by',
  level: 0,
  cost: 25000000,
  value: 0,
  growthRate: 1, // ?
}, {
  id: 17,
  name: 'Ebony Rune Of Blood',
  description: 'Increase damage per second by',
  level: 0,
  cost: 100000000,
  value: 0,
  growthRate: 782000,
}, {
  id: 18,
  name: 'Maelstrom Shield',
  description: 'Increase damage per second by',
  level: 0,
  cost: 800000000,
  value: 0,
  growthRate: 3721000,
}, {
  id: 19,
  name: 'Spy Of The Order Of The Ebony',
  description: 'Increase damage per second by',
  level: 0,
  cost: 6500000000,
  value: 0,
  growthRate: 17010000,
}, {
  id: 20,
  name: 'Sacrifice Knife',
  description: 'Increase damage per second by',
  level: 0,
  cost: 50000000000,
  value: 0,
  growthRate: 69480000,
}];
