const killedMonsters = 'total.kills.monsters';
const killedBosses = 'total.kills.bosses';
const clickedTimes = 'total.clicks';
const purchasedUpgradesLevels = 'total.purchasedLevels';

export const initialAchievements = [{
  id: 1,
  name: 'Hunter',
  description: 'Kill 10 monsters',
  received: false,
  hidden: false,
  property: killedMonsters,
  value: 10,
}, {
  id: 2,
  name: 'Killer',
  description: 'Kill 1K monsters',
  received: false,
  hidden: false,
  property: killedMonsters,
  value: 1000,
}, {
  id: 3,
  name: 'Slayer',
  description: 'Kill 10K monsters',
  received: false,
  hidden: false,
  property: killedMonsters,
  value: 10000,
}, {
  id: 4,
  name: 'Slaughterer',
  description: 'Kill 100K monsters',
  received: false,
  hidden: false,
  property: killedMonsters,
  value: 100000,
}, {
  id: 5,
  name: 'Homicide',
  description: 'Kill 1 boss',
  received: false,
  hidden: false,
  property: killedBosses,
  value: 1,
}, {
  id: 6,
  name: 'Atheist',
  description: 'Kill 10 bosses',
  received: false,
  hidden: false,
  property: killedBosses,
  value: 10,
}, {
  id: 7,
  name: 'Murderer',
  description: 'Kill 50 bosses',
  received: false,
  hidden: false,
  property: killedBosses,
  value: 50,
}, {
  id: 8,
  name: 'Assassin',
  description: 'Kill 100 bosses',
  received: false,
  hidden: false,
  property: killedBosses,
  value: 100,
}, {
  id: 9,
  name: 'come up with',
  description: 'Click 100 times',
  received: false,
  hidden: false,
  property: clickedTimes,
  value: 100,
}, {
  id: 10,
  name: 'come up with',
  description: 'Click 1K times',
  received: false,
  hidden: false,
  property: clickedTimes,
  value: 1000,
}, {
  id: 11,
  name: 'come up with',
  description: 'Click 10K times',
  received: false,
  hidden: false,
  property: clickedTimes,
  value: 10000,
}, {
  id: 12,
  name: 'come up with',
  description: 'Click 100K times',
  received: false,
  hidden: false,
  property: clickedTimes,
  value: 100000,
}, {
  id: 13,
  name: 'come up with',
  description: 'Buy 100 upgrades',
  received: false,
  hidden: false,
  property: purchasedUpgradesLevels,
  value: 100,
}, {
  id: 14,
  name: 'come up with',
  description: 'Buy 500 upgrades',
  received: false,
  hidden: false,
  property: purchasedUpgradesLevels,
  value: 500,
}, {
  id: 15,
  name: 'come up with',
  description: 'Buy 2.5K upgrades',
  received: false,
  hidden: false,
  property: purchasedUpgradesLevels,
  value: 2500,
}, {
  id: 16,
  name: 'come up with',
  description: 'Buy 10K upgrades',
  received: false,
  hidden: false,
  property: purchasedUpgradesLevels,
  value: 10000,
}, {
  id: 17,
  name: 'come up with',
  description: 'Kill 666 monsters',
  received: false,
  hidden: true,
  property: killedMonsters,
  value: 666,
}, {
  id: 18,
  name: 'come up with',
  description: 'Kill 666 bosses',
  received: false,
  hidden: true,
  property: killedBosses,
  value: 666,
}, {
  id: 19,
  name: 'come up with',
  description: 'Click 666 times',
  received: false,
  hidden: true,
  property: clickedTimes,
  value: 666,
}, {
  id: 20,
  name: 'come up with',
  description: 'Buy 666 upgrades',
  received: false,
  hidden: true,
  property: purchasedUpgradesLevels,
  value: 666,
}];
