const killedMonsters = 'total.kills.monsters';
const killedBosses = 'total.kills.bosses';
const clickedTimes = 'total.clicks';
const purchasedUpgradesLevels = 'total.purchasedLevels';
const earnedSapphires = 'total.sapphires';
const reincarnatedTimes = 'total.reincarnatedTimes';
const earnedGold = 'total.gold';
const dealedDamage = 'total.damage';

export const initialAchievements = [{
  id: 1,
  name: 'Hunter',
  description: 'Kill 10 monsters',
  received: false,
  hidden: false,
  property: killedMonsters,
  value: 10,
}, {
  id: 2,
  name: 'Killer',
  description: 'Kill 1K monsters',
  received: false,
  hidden: false,
  property: killedMonsters,
  value: 1000,
}, {
  id: 3,
  name: 'Slayer',
  description: 'Kill 10K monsters',
  received: false,
  hidden: false,
  property: killedMonsters,
  value: 10000,
}, {
  id: 4,
  name: 'Slaughterer',
  description: 'Kill 100K monsters',
  received: false,
  hidden: false,
  property: killedMonsters,
  value: 100000,
}, {
  id: 5,
  name: 'Homicide',
  description: 'Kill 1 boss',
  received: false,
  hidden: false,
  property: killedBosses,
  value: 1,
}, {
  id: 6,
  name: 'Atheist',
  description: 'Kill 10 bosses',
  received: false,
  hidden: false,
  property: killedBosses,
  value: 10,
}, {
  id: 7,
  name: 'Murderer',
  description: 'Kill 50 bosses',
  received: false,
  hidden: false,
  property: killedBosses,
  value: 50,
}, {
  id: 8,
  name: 'Assassin',
  description: 'Kill 100 bosses',
  received: false,
  hidden: false,
  property: killedBosses,
  value: 100,
}, {
  id: 9,
  name: 'come up with',
  description: 'Click 100 times',
  received: false,
  hidden: false,
  property: clickedTimes,
  value: 100,
}, {
  id: 10,
  name: 'come up with',
  description: 'Click 1K times',
  received: false,
  hidden: false,
  property: clickedTimes,
  value: 1000,
}, {
  id: 11,
  name: 'come up with',
  description: 'Click 10K times',
  received: false,
  hidden: false,
  property: clickedTimes,
  value: 10000,
}, {
  id: 12,
  name: 'come up with',
  description: 'Click 100K times',
  received: false,
  hidden: false,
  property: clickedTimes,
  value: 100000,
}, {
  id: 13,
  name: 'come up with',
  description: 'Buy 100 upgrades',
  received: false,
  hidden: false,
  property: purchasedUpgradesLevels,
  value: 100,
}, {
  id: 14,
  name: 'come up with',
  description: 'Buy 500 upgrades',
  received: false,
  hidden: false,
  property: purchasedUpgradesLevels,
  value: 500,
}, {
  id: 15,
  name: 'come up with',
  description: 'Buy 2.5K upgrades',
  received: false,
  hidden: false,
  property: purchasedUpgradesLevels,
  value: 2500,
}, {
  id: 16,
  name: 'come up with',
  description: 'Buy 10K upgrades',
  received: false,
  hidden: false,
  property: purchasedUpgradesLevels,
  value: 10000,
}, {
  id: 17,
  name: 'come up with',
  description: 'Kill 666 monsters',
  received: false,
  hidden: true,
  property: killedMonsters,
  value: 666,
}, {
  id: 18,
  name: 'come up with',
  description: 'Kill 666 bosses',
  received: false,
  hidden: true,
  property: killedBosses,
  value: 666,
}, {
  id: 19,
  name: 'come up with',
  description: 'Click 666 times',
  received: false,
  hidden: true,
  property: clickedTimes,
  value: 666,
}, {
  id: 20,
  name: 'come up with',
  description: 'Buy 666 upgrades',
  received: false,
  hidden: true,
  property: purchasedUpgradesLevels,
  value: 666,
}, {
  id: 21,
  name: 'Lucky bastard',
  description: 'Get your first sapphire',
  received: false,
  hidden: false,
  property: earnedSapphires,
  value: 1,
}, {
  id: 22,
  name: 'Miner',
  description: 'Get 50 sapphires',
  received: false,
  hidden: false,
  property: earnedSapphires,
  value: 50,
}, {
  id: 23,
  name: 'Jeweler',
  description: 'Get 250 sapphires',
  received: false,
  hidden: false,
  property: earnedSapphires,
  value: 250,
}, {
  id: 24,
  name: 'King of sparks',
  description: 'Get 1000 sapphires',
  received: false,
  hidden: false,
  property: earnedSapphires,
  value: 1000,
}, {
  id: 25,
  name: 'I\'m alive',
  description: 'Reincarnate 1 time',
  received: false,
  hidden: false,
  property: reincarnatedTimes,
  value: 1,
}, {
  id: 26,
  name: 'Immortal',
  description: 'Reincarnate 5 times',
  received: false,
  hidden: false,
  property: reincarnatedTimes,
  value: 5,
}, {
  id: 27,
  name: 'Legend',
  description: 'Reincarnate 25 times',
  received: false,
  hidden: false,
  property: reincarnatedTimes,
  value: 25,
}, {
  id: 28,
  name: 'Deity',
  description: 'Reincarnate 50 times',
  received: false,
  hidden: false,
  property: reincarnatedTimes,
  value: 50,
}, {
  id: 29,
  name: 'Scrooge McDuck',
  description: 'Earn 1K gold',
  received: false,
  hidden: false,
  property: earnedGold,
  value: 1000,
}, {
  id: 30,
  name: 'Rich',
  description: 'Earn 1M gold',
  received: false,
  hidden: false,
  property: earnedGold,
  value: 1000000,
}, {
  id: 31,
  name: 'Treasurer',
  description: 'Earn 1B gold',
  received: false,
  hidden: false,
  property: earnedGold,
  value: 1000000000,
}, {
  id: 32,
  name: 'Croesus',
  description: 'Earn 1T gold',
  received: false,
  hidden: false,
  property: earnedGold,
  value: 1000000000000,
}, {
  id: 33,
  name: 'Pain in the leg',
  description: 'Deal 1K damage',
  received: false,
  hidden: false,
  property: dealedDamage,
  value: 1000,
}, {
  id: 34,
  name: 'Bonecrusher',
  description: 'Deal 1M damage',
  received: false,
  hidden: false,
  property: dealedDamage,
  value: 1000000,
}, {
  id: 35,
  name: 'Thug',
  description: 'Deal 1B damage',
  received: false,
  hidden: false,
  property: dealedDamage,
  value: 1000000000,
}, {
  id: 36,
  name: 'Undertaker',
  description: 'Deal 1T damage',
  received: false,
  hidden: false,
  property: dealedDamage,
  value: 1000000000000,
}];
